### ISSUE TITLE
Block styles missing in templates editor in Firefox

### ISSUE THREAD

**Issue by davidLpt** [nk-crew/ghostkit#146]
Hi,
I'm trying to use ghostkit grid in the new Appearance->Editor (Full Site Editing) but when I assign different width to the columns inside the grid, they are always displayed with 100% width. I notice that all the ghoskit styles like 'ghostkit-col-1' are actually not loaded. They are loaded in the block editor page though.
Is there a way to get them to load in this new editor that is quite useful to edit template-parts.....?

Thanks in advance for you reply

**Comment by nk-o** [comment]
Fixed in https://github.com/nk-crew/ghostkit/commit/dafc850e082eae3e895c941bea66e478122e1e11

**Comment by davidLpt** [comment]
Thx, but just so you know, it still doesn't work in the template or template-part editor.

**Comment by nk-o** [comment]
ofc, because no plugin update released with this fix yet

**Comment by davidLpt** [comment]
Hi, I downloaded the update of the plugin but no luck for the template-part editor, it's still broken..

**Comment by nk-o** [comment]
Hey. Please, provide detailed information to reproduce this issue.

I have checked it with the `Twenty Twenty-Two` theme in WordPress 5.9 and it is working just fine.

**Comment by davidLpt** [comment]
ok I investigated a bit further and it seems it's a browser related issue. It works perfectly on Chrome or Brave, the problem happens with Firefox. I tried with the 97.0 version and the last update 97.0.1. I see that the styles for the editor are loaded but they are not applied....... I got no clue why....

**Comment by nk-o** [comment]
Example:

![image](https://user-images.githubusercontent.com/14810891/154817224-aaa6d25f-8f60-4f99-a5be-0711b4c1839b.png)

**Comment by casperdeboer** [comment]
I also noticed that since the latest available ghost kit update (2.22.3) I am not able to update a page that contains the video module from the Nk template library. When removing the video section it will update, but with it, it won't and shows the Updating failed error. This happens in Firefox, Safari, and Chrome.

**Comment by nk-o** [comment]
Finally fixed in https://github.com/nk-crew/ghostkit/commit/e376f4515db03deb4f3ad6fcb2b2defc6083ef57
