### ISSUE TITLE
Automatic filling of the id field

### ISSUE THREAD

**Issue by ProNoiser** [nk-crew/ghostkit#223]
Hello!
When plugin is activated I have automatic filling of the id field with the content of the header itself for any headings on the page. Example: If I have the title "My best work" in any of the title tags (<h*></h*>), then its id will be the same. <h* id="my-best-work">My best work</h*>. When you try to clear the id field for the header, it is still automatically filled with its contents. When I deactivate the plugin, everything works fine and nothing is filled in without my knowledge. Why is this happening and is it possible to correct this behavior?
Thanks!

**Comment by nk-o** [comment]
We fixed the problem, which is why your issue was closed. The fix will be available in the next plugin update.

**Comment by ProNoiser** [comment]
Hello! You are not fixed this bug... It's very pool... I tired fix manually this problem in my project. I remove your plugin. :-(

**Comment by nk-o** [comment]
Sorry for this. I also had to remove the code where we overrode the Gutenberg setting a long time ago. The plugin has been updated with a fix.
